USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/huawei/c8813/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := unknown
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := c8813

BOARD_KERNEL_CMDLINE := androidboot.hardware=huawei loglevel=1
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
# /dev/block/mmcblk0p17 /system ext4 1048576*1024 = 1073741824
# /dev/block/mmcblk0p18 /data ext4 1179648*1024 = 1207959552
# /dev/block/mmcblk0p12 boot mtd 8192*1024 = 8388608
# /dev/block/mmcblk0p5 recovery mtd 20480*1024 = 20971520
BOARD_BOOTIMAGE_PARTITION_SIZE := 8388608 # 8MB
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 20971520 # 20MB
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1073741824 # 1024MB
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1207959552 # 1152MB
BOARD_FLASH_BLOCK_SIZE := 131072 # BOARD_KERNEL_PAGESIZE*64

TARGET_PREBUILT_KERNEL := device/huawei/c8813/kernel

BOARD_HAS_NO_SELECT_BUTTON := true
#
# Additional config
#

# Recovery
RECOVERY_NAME := ClockworkMod Recovery
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"
BOARD_HAS_NO_SELECT_BUTTON := true
#BOARD_UMS_LUNFILE := true
#BOARD_RECOVERY_ALWAYS_WIPES := true
#BOARD_RECOVERY_HANDLES_MOUNT := true
#BOARD_TOUCH_RECOVERY := true
#RECOVERY_EXTEND_NANDROID_MENU := true
#TARGET_USE_CUSTOM_LUN_FILE_PATH := true
#TARGET_DEVICE := true
#BOARD_RECOVERY_DEFINES :=
BOARD_CUSTOM_RECOVERY_KEYMAPPING := ../../device/huawei/c8813/recovery/keys.c
BOARD_CUSTOM_GRAPHICS := ../../../device/huawei/c8813/recovery/graphics.c
#TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
BOARD_USE_CUSTOM_RECOVERY_FONT := \"font_10x18.h\" # default is font_10x18.h
#BOARD_USES_BML_OVER_MTD := true
TARGET_USERIMAGES_USE_EXT4 := ture
TARGET_RECOVERY_FSTAB := device/huawei/c8813/recovery/recovery.fstab # default is recovery.fstab
#BOARD_RECOVERY_RFS_CHECK := true

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/huawei/c8813/include/bluetooth
BOARD_HAVE_BLUETOOTH_BCM := true
#TARGET_SIMULATOR := true
#BLUETOOTH_HCI_USE_MCT := true
#BOARD_USES_ALSA_AUDIO := true
#TARGET_QCOM_AUDIO_VARIANT := caf

# WIFI
#WPA_SUPPLICANT_VERSION := VER_0_6_X
WPA_SUPPLICANT_VERSION := VER_0_8_X
#BOARD_WPA_SUPPLICANT_DRIVER :=
WIFI_DRIVER_MODULE_PATH := "/system/wifi/dhd_4330.ko"
#WIFI_DRIVER_MODULE_ARG :=
#WIFI_DRIVER_MODULE_AP_ARG :=
#WIFI_FIRMWARE_LOADER :=
#WIFI_DRIVER_LOADER_DELAY :=
WIFI_DRIVER_FW_PATH_AP := "/system/wifi/fw_4330_b2.bin"
WIFI_DRIVER_FW_PATH_STA := "/system/wifi/fw_4330_b2.bin"
WIFI_DRIVER_FW_PATH_P2P := "/system/wifi/fw_4330_b2.bin"
WIFI_DRIVER_MODULE_ARG := "iface_name=eth0 firmware_path=/system/wifi/fw_4330_b2.bin nvram_path=/system/wifi/nvram_4330.txt"
#WIFI_DRIVER_FW_PATH_PARAM :=
WIFI_DRIVER_MODULE_NAME := "dhd_4330"
#WIFI_EXT_MODULE_PATH :=
#WIFI_EXT_MODULE_ARG :=
#WIFI_EXT_MODULE_NAME :=
#BOARD_HOSTAPD_DRIVER :=
#BOARD_WLAN_DEVICE := bcmdhd
#BOARD_LEGACY_NL80211_STA_EVENTS := true
#BOARD_NO_APSME_ATTR := true
#BOARD_WLAN_DEVICE := qcwcn
