USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/huawei/c8813/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_BOARD_PLATFORM := msm7627a
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := false
TARGET_ARCH_VARIANT := armv7-a-neon
# cortex-a9 is used to take advantage of NEON optimizations
TARGET_ARCH_VARIANT_CPU := cortex-a9
TARGET_ARCH_VARIANT_FPU := neon
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := c8813
TARGET_OTA_ASSERT_DEVICE := c8813,hwc8813

BOARD_KERNEL_CMDLINE := androidboot.hardware=huawei loglevel=1
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
# /dev/block/mmcblk0p17 /system ext4 1048576*1024 = 1073741824
# /dev/block/mmcblk0p18 /data ext4 1179648*1024 = 1207959552
# /dev/block/mmcblk0p12 boot mtd 8192*1024 = 8388608
# /dev/block/mmcblk0p5 recovery mtd 20480*1024 = 20971520
BOARD_BOOTIMAGE_PARTITION_SIZE := 8388608 # 8MB
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 20971520 # 20MB
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1073741824 # 1024MB
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1207959552 # 1152MB
BOARD_FLASH_BLOCK_SIZE := 131072 # BOARD_KERNEL_PAGESIZE*64

# Partitions
BOARD_DATA_DEVICE := /dev/block/mmcblk0p18
BOARD_DATA_FILESYSTEM := ext4
BOARD_DATA_FILESYSTEM_OPTIONS := rw
BOARD_SYSTEM_DEVICE := /dev/block/mmcblk0p17
BOARD_SYSTEM_FILESYSTEM := ext4
BOARD_SYSTEM_FILESYSTEM_OPTIONS := rw
BOARD_CACHE_DEVICE := /dev/block/mmcblk0p15
BOARD_CACHE_FILESYSTEM := ext4
BOARD_CACHE_FILESYSTEM_OPTIONS := rw
BOARD_USES_MMCUTILS := true


TARGET_PREBUILT_KERNEL := device/huawei/c8813/kernel

#
# Additional config
#

# Recovery
RECOVERY_NAME := ClockworkMod Recovery(TTLD)
BOARD_HAS_NO_SELECT_BUTTON := true
#BOARD_RECOVERY_ALWAYS_WIPES := true
#BOARD_RECOVERY_HANDLES_MOUNT := true
#RECOVERY_EXTEND_NANDROID_MENU := true
#TARGET_USE_CUSTOM_LUN_FILE_PATH := true
#TARGET_DEVICE := true
#BOARD_RECOVERY_DEFINES :=
#BOARD_RECOVERY_RFS_CHECK := true
BOARD_USES_BML_OVER_MTD := true
TARGET_USERIMAGES_USE_EXT4 := ture
#BOARD_TOUCH_RECOVERY := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
BOARD_CUSTOM_RECOVERY_KEYMAPPING := ../../device/huawei/c8813/recovery/keys.c
BOARD_CUSTOM_GRAPHICS := ../../../device/huawei/c8813/recovery/graphics.c
#BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\" # default is font_10x18.h
TARGET_RECOVERY_INITRC := device/huawei/c8813/recovery/init.rc
TARGET_RECOVERY_FSTAB := device/huawei/c8813/recovery/recovery.fstab # default is recovery.fstab
BOARD_UMS_LUNFILE := /sys/class/android_usb/android0/f_mass_storage/lun%d/file

# Audio
TARGET_QCOM_AUDIO_VARIANT := true
#TARGET_PROVIDES_LIBAUDIO := true
BOARD_USES_ALSA_AUDIO := true
#TARGET_QCOM_AUDIO_VARIANT := caf

# Lights
TARGET_PROVIDES_LIBLIGHTS := true

# Camera
TARGET_PROVIDES_CAMERA_HAL := true
V4L2_BASED_LIBCAM := true
BOARD_NEEDS_MEMORYHEAPPMEM := true
COMMON_GLOBAL_CFLAGS += -DICS_CAMERA_BLOB

# GPS
BOARD_USES_QCOM_GPS := true
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50000
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := msm7627a

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true
#TARGET_SIMULATOR := true
#BLUETOOTH_HCI_USE_MCT := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/huawei/c8813/include/bluetooth
#BOARD_BLUEDROID_VENDOR_CONF := device/huawei/c8813/bluetooth/vnd_c8813.txt

# WIFI
#WPA_SUPPLICANT_VERSION := VER_0_6_X
WPA_SUPPLICANT_VERSION := VER_0_8_X
#BOARD_WLAN_DEVICE := qcwcn
BOARD_WLAN_DEVICE := bcmdhd
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_bcmdhd
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_bcmdhd
BOARD_LEGACY_NL80211_STA_EVENTS := true
#BOARD_NO_APSME_ATTR := true
WIFI_DRIVER_FW_PATH_AP := "/system/wifi/fw_4330_b2.bin"
WIFI_DRIVER_FW_PATH_STA := "/system/wifi/fw_4330_b2.bin"
WIFI_DRIVER_FW_PATH_P2P := "/system/wifi/fw_4330_b2.bin"
WIFI_DRIVER_MODULE_PATH := "/system/wifi/dhd_4330.ko"
WIFI_DRIVER_MODULE_ARG := "iface_name=eth0 firmware_path=/system/wifi/fw_4330_b2.bin nvram_path=/system/wifi/nvram_4330.txt"
#WIFI_FIRMWARE_LOADER :=
#WIFI_DRIVER_LOADER_DELAY :=
#WIFI_DRIVER_MODULE_AP_ARG :=
#WIFI_DRIVER_FW_PATH_PARAM :=
WIFI_DRIVER_MODULE_NAME := "dhd_4330"
WIFI_EXT_MODULE_NAME := "cfg80211"
WIFI_EXT_MODULE_PATH := "/system/lib/modules/cfg80211.ko"
#WIFI_EXT_MODULE_ARG :=

# QCOM hardware
BOARD_USES_QCOM_HARDWARE := true
COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE

TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
BOARD_HAS_NO_MISC_PARTITION := true

TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp

# Optimisations used by Qualcomm
TARGET_CORTEX_CACHE_LINE_32 := true
TARGET_USE_SPARROW_BIONIC_OPTIMIZATION := true
TARGET_AVOID_DRAW_TEXTURE_EXTENSION := true
TARGET_USES_16BPPSURFACE_FOR_OPAQUE := true

ARCH_ARM_HAVE_32_BYTE_CACHE_LINES := true

TARGET_USES_ION := false

#TARGET_SPECIFIC_HEADER_PATH := device/huawei/c8813/include

# RIL
#BOARD_RIL_CLASS := ../../../device/huawei/c8813/ril/

# Graphics
COMMON_GLOBAL_CFLAGS += -DANCIENT_GL
BOARD_EGL_CFG := device/huawei/c8813/config/egl.cfg
USE_OPENGL_RENDERER := true
BOARD_ADRENO_DECIDE_TEXTURE_TARGET := true
BOARD_AVOID_DRAW_TEXTURE_EXTENSION := true
BOARD_USE_SKIA_LCDTEXT := true
TARGET_NO_HW_OVERLAY := true
TARGET_QCOM_DISPLAY_VARIANT := legacy

# Video
COMMON_GLOBAL_CFLAGS += -DQCOM_ICS_DECODERS -DQCOM_LEGACY_OMX -DQCOM_NO_SECURE_PLAYBACK

# Web Rendering
ENABLE_WEBGL := true
TARGET_FORCE_CPU_UPLOAD := true

# USB
#TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/class/android_usb/android0/f_mass_storage/lun%d/file
#TARGET_USE_CUSTOM_SECOND_LUN_NUM := 1
#BOARD_USE_USB_MASS_STORAGE_SWITCH := true
#BOARD_VOLD_MAX_PARTITIONS := 19
#BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true

# FM Radio
BOARD_HAVE_FM_RADIO := true
BOARD_FM_DEVICE := bcm4330
BOARD_GLOBAL_CFLAGS += -DHAVE_FM_RADIO
